package pojo;

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Purchase {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.purchase_id
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer purchaseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.commodity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private String commodity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.is_agree
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer isAgree;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.supplier
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private String supplier;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.quantity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer quantity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.amount_money
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Float amountMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.payment_method
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer paymentMethod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.is_pay
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer isPay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.has_take_goods
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Integer hasTakeGoods;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.operator
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private String operator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column purchase.purchase_time
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	private Date purchaseTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.purchase_id
	 *
	 * @return the value of purchase.purchase_id
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer getPurchaseId() {
		return purchaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.purchase_id
	 *
	 * @param purchaseId
	 *            the value for purchase.purchase_id
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setPurchaseId(Integer purchaseId) {
		this.purchaseId = purchaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.commodity
	 *
	 * @return the value of purchase.commodity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public String getCommodity() {
		return commodity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.commodity
	 *
	 * @param commodity
	 *            the value for purchase.commodity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setCommodity(String commodity) {
		this.commodity = commodity == null ? null : commodity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.is_agree
	 *
	 * @return the value of purchase.is_agree
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer getIsAgree() {
		return isAgree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.is_agree
	 *
	 * @param isAgree
	 *            the value for purchase.is_agree
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setIsAgree(Integer isAgree) {
		this.isAgree = isAgree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.supplier
	 *
	 * @return the value of purchase.supplier
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.supplier
	 *
	 * @param supplier
	 *            the value for purchase.supplier
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier == null ? null : supplier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.quantity
	 *
	 * @return the value of purchase.quantity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.quantity
	 *
	 * @param quantity
	 *            the value for purchase.quantity
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.amount_money
	 *
	 * @return the value of purchase.amount_money
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Float getAmountMoney() {
		return amountMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.amount_money
	 *
	 * @param amountMoney
	 *            the value for purchase.amount_money
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setAmountMoney(Float amountMoney) {
		this.amountMoney = amountMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.payment_method
	 *
	 * @return the value of purchase.payment_method
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer getPaymentMethod() {
		return paymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.payment_method
	 *
	 * @param paymentMethod
	 *            the value for purchase.payment_method
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setPaymentMethod(Integer paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.is_pay
	 *
	 * @return the value of purchase.is_pay
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer getIsPay() {
		return isPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.is_pay
	 *
	 * @param isPay
	 *            the value for purchase.is_pay
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setIsPay(Integer isPay) {
		this.isPay = isPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.has_take_goods
	 *
	 * @return the value of purchase.has_take_goods
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public Integer gethasTakeGoods() {
		return hasTakeGoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.has_take_goods
	 *
	 * @param hasTakeGoods
	 *            the value for purchase.has_take_goods
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void sethasTakeGoods(Integer hasTakeGoods) {
		this.hasTakeGoods = hasTakeGoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.operator
	 *
	 * @return the value of purchase.operator
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.operator
	 *
	 * @param operator
	 *            the value for purchase.operator
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column purchase.purchase_time
	 *
	 * @return the value of purchase.purchase_time
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getPurchaseTime() {
		return purchaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column purchase.purchase_time
	 *
	 * @param purchaseTime
	 *            the value for purchase.purchase_time
	 *
	 * @mbggenerated Tue Sep 10 10:00:38 CST 2019
	 */
	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Purchase [purchaseId=");
		builder.append(purchaseId);
		builder.append(", commodity=");
		builder.append(commodity);
		builder.append(", isAgree=");
		builder.append(isAgree);
		builder.append(", supplier=");
		builder.append(supplier);
		builder.append(", quantity=");
		builder.append(quantity);
		builder.append(", amountMoney=");
		builder.append(amountMoney);
		builder.append(", paymentMethod=");
		builder.append(paymentMethod);
		builder.append(", isPay=");
		builder.append(isPay);
		builder.append(", hasTakeGoods=");
		builder.append(hasTakeGoods);
		builder.append(", operator=");
		builder.append(operator);
		builder.append(", purchaseTime=");
		builder.append(purchaseTime);
		builder.append("]");
		return builder.toString();
	}
	
}