package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Purchase;
import pojo.PurchaseExample;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int countByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int deleteByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int deleteByPrimaryKey(Integer purchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int insertSelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    List<Purchase> selectByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    Purchase selectByPrimaryKey(Integer purchaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int updateByExample(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int updateByPrimaryKeySelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Tue Sep 10 10:00:38 CST 2019
     */
    int updateByPrimaryKey(Purchase record);
}